# 前端 Dockerfile
FROM node:14 AS build
WORKDIR /app
COPY blog-view/package*.json ./
RUN npm install
COPY blog-view/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY blog-view/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
